apiVersion: v1
kind: ConfigMap
metadata:
  name: comm-simulator-config
  namespace: {{ .Values.appNamespace }}
data:
  NODE_ENV: {{ .Values.config.env }}
  PORT: {{ .Values.config.http.port | quote }}