export enum ACTION_TYPES {
  SET_WORKERS = "SET_WORKERS",
  SELECT_WORKER = "SELECT_WORKER",
  UPDATE_WORKER = "UPDATE_WORKER",
  DESELECT_WORKER = "DESELECT_WORKER",
  CONNECT_WORKER = "CONNECT_WORKER",
  LOGOUT = "LOGOUT",
  UPDATE_WORKER_STATUS = "UPDATE_WORKER_STATUS",
  CONNECT_ALL = "CONNECT_ALL",
  DISCONNECT_ALL = "DISCONNECT_ALL",
}

export enum TASK_ACTION_TYPES {
  ADD_TASK = "ADD_TASK",
  UPDATE_TASK = "UPDATE_TASK",
  REMOVE_TASK = "REMOVE_TASK",
}

export enum TASK_FORM_ACTION_TYPES {
  OPEN_TASK_FORM = "OPEN_TASK_FORM",
  CANCEL_TASK_FORM = "CANCEL_TASK_FORM",
  CONFIRM_TASK_FORM = "CONFIRM_TASK_FORM",
}

export enum APP_ACTION_TYPES {
  SET_USER = "SET_USER",
  SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED",
}

export enum INTEGRATION_TYPES{
  SET_INTEGRATIONS = "SET_INTEGRATIONS",
}